### ISSUE TITLE
Planning on how we organise our development with Hypothes.is

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/infrastructure#18]
### What is the situation?
We are forming and independent development team, that contributes to the Hypothes.is project to make it the foundation it needs to be for itself and us.
The development and pull requests take place on [the Hypothes.is fork in our repo](https://github.com/WorldBrain/Webmarks).
From there on we push our updates downstream to [the core Hypothes.is repo](https://github.com/hypothesis/h).

Our main objective is to collaborate with the Hypothes.is development so well, that we ideally only integrate all our work into their repo
But, it is possible that some changes, we see as necessary, cannot be integrated (yet) into Hypothes.is or are unwanted.

##### Upstream update with minimised merge conflicts
An initial idea was to keep a clean fork of Hypothes.is on which we can integrate upstream from Hypothes.is.
Our additions should be attached in a modular way, so they can be easily removed and reused (by hypothes.is) if they want to implement them.

### To-Dos:

- [ ] [Setting up hypothes.is](https://github.com/WorldBrain/START-HERE/blob/master/HOW-TO-SETUP.md) in your local environment
- [ ] Exploring the code
- [ ] Engaging in discussion in this issue about how this can be implemented.

Thanks for your help and input! :smile: :+1:
